### ISSUE TITLE
Request option "all fields" if not set in cachDoc().

### ISSUE THREAD

**Issue by thearabbit** [jeanfredrik/meteor-denormalize#6]
I would like to request you for `all fields` if not set in `cachDoc()`.

``` js
Comments.cacheDoc('post', Posts, [all fields if not set]);
```

**Comment by jeanfredrik** [comment]
I purposly left that option out since it could lead to circular executions. For example if you make a colelction of people and each person can have a best friend that is in the same collection, and decide you want to copy all fields, it would look like this:

``` js
People.cacheDoc('bestFriend', People, ALL_FIELDS);
```

But then when a person is updated, it will start a chain of caching, resulting in a document like this:

``` js
{
    _id: 1,
    name: 'Adam',
    bestFriend_id: 2,
    _bestFriend: {
        _id: 2,
        name: 'Beatrice',
        bestFriend_id: 3,
        _bestFriend: {
            _id: 3,
            name: 'Charlie',
            bestFriend_id: 4,
            // etc...
        }
    }
}
```

If Charlie had Adam as best friend, the chain would turn into an endless loop. This can also happen if to collections reference eachother.

Another advantage with this approach is that hooks are not fired if none of the watched fields have been changed. `People.cacheDoc('bestFriend', People, ALL_FIELDS);` would have to run on any update, decreasing performance. Just cache the fields you actually need.

**Comment by thearabbit** [comment]
Thanks for your replay, I waiting for your update.
I want to cache all fields of `bestFriend_id: 2` only, not `bestFriend_id: 3, 4, 5...`
